services:
  - type: web
    name: bio-quantum-api
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node apiBridge_with_token_endpoint.cjs
    envVars:
      - key: NODE_VERSION
        value: 22.1.0

