services:
  - type: web
    name: bio-quantum-trading-platform
    env: python
    buildCommand: pip install -r backend/bio_quantum_api/requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port 10000
    workingDir: backend/bio_quantum_api
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend/bio_quantum_api
    healthCheckPath: /health
    autoDeploy: true


